spring:
  config:
    activate:
      on-profile: dev
  application:
    name: PostSociableSphereDev
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  server:
    port: 8080
  logging:
    level:
      root: DEBUG
  data:
    r2dbc:
      repositories:
        enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
users:
  url: http://localhost:8081
  get-by-id: /v1/users/
  get-by-ids: /v1/users/usersByIds