spring:
  config:
    activate:
      on-profile: prod
  application:
    name: PostSociableSphere
  r2dbc:
    url: r2dbc:postgresql://jse:socialsphere@postgresql-jse.alwaysdata.net:5432/jse_post
    username: jse
    password: socialsphere
  data:
    r2dbc:
      repositories:
        enabled: true
  sql:
    init:
      mode: never
server:
  port: 8080
users:
  url: http://localhost:8081
  get-by-id: /v1/users/
  get-by-ids: /v1/users/usersByIds

