spring:
  config:
    activate:
      on-profile: prod
  application:
    name: PostSociableSphere
  r2dbc:
    url: r2dbc:postgresql-jse.alwaysdata.net:5432/jse_post
    username: jse
    password: socialsphere
  server:
    port: 8081
  logging:
    level:
      root: DEBUG
  data:
    r2dbc:
      repositories:
        enabled: true
  sql:
    init:
      mode: never

users:
  url: https://localhost:8081
  get-by-id: /users/

